In [2]:
!pip install pymupdf

Collecting pymupdf
  Downloading pymupdf-1.27.2.3-cp310-abi3-win_amd64.whl.metadata (24 kB)
Downloading pymupdf-1.27.2.3-cp310-abi3-win_amd64.whl (19.2 MB)
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/19.2 MB 4.2 MB/s eta 0:00:05
   -- ------------------------------------- 1.3/19.2 MB 4.0 MB/s eta 0:00:05
   ---- ----------------------------------- 2.1/19.2 MB 3.9 MB/s eta 0:00:05
   ----- ---------------------------------- 2.6/19.2 MB 3.9 MB/s eta 0:00:05
   ------- -------------------------------- 3.4/19.2 MB 3.7 MB/s eta 0:00:05
   -------- ------------------------------- 4.2/19.2 MB 3.7 MB/s eta 0:00:05
   ---------- ----------------------------- 5.0/19.2 MB 3.7 MB/s eta 0:00:04
   ----------- ---------------------------- 5.8/19.2 MB 3.8 MB/s eta 0:00:04
   -------------- ------------------------- 6.8/19.2 MB 3.8 MB/s eta 0:00:04
   --------------- ------------------------ 7.6/19.2 MB 3.8 MB/s eta 0:00:04
   ----------------- ---------------------- 8.4/19.2 MB 3.8 MB/s eta 0:00:03
   ------------------- -------------------- 9.2/19.2 MB 3.8 MB/s eta 0:00:03
   --------------------- ------------------ 10.2/19.2 MB 3.8 MB/s eta 0:00:03
   ---------------------- ----------------- 11.0/19.2 MB 3.8 MB/s eta 0:00:03
   ------------------------ --------------- 11.8/19.2 MB 3.8 MB/s eta 0:00:02
   -------------------------- ------------- 12.6/19.2 MB 3.8 MB/s eta 0:00:02
   --------------------------- ------------ 13.4/19.2 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 14.2/19.2 MB 3.8 MB/s eta 0:00:02
   ------------------------------- -------- 14.9/19.2 MB 3.8 MB/s eta 0:00:02
   --------------------------------- ------ 16.0/19.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------- ----- 16.8/19.2 MB 3.8 MB/s eta 0:00:01
   ----------------------------------- ---- 17.3/19.2 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 18.1/19.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  18.9/19.2 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 19.2/19.2 MB 3.7 MB/s  0:00:05
Installing collected packages: pymupdf
Successfully installed pymupdf-1.27.2.3

In [3]:
# ingestion/load_pdf.py

import fitz
from pathlib import Path

folder = Path("data_sources/pdf_reports")

for file in folder.glob("*.pdf"):

    doc = fitz.open(file)

    text = ""

    for page in doc:
        text += page.get_text()

    print(f"\n--- {file.name} ---")
    print(text[:1000])

In [6]:
doc = fitz.open(r"D:\Finance ChatBot\data_source\pdf_reports\Marwan Tamer Resume.pdf")

text = ""

for page in doc:
    text += page.get_text()

print(text)

MARWAN TAMER SAYED
Cairo, Egypt | marwantamer004@gmail.com | 01553278930 | LinkedIn |  GitHub
Summary
Aspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python,
machine learning, and statistical analysis. Skilled in data preprocessing, feature engineering, and model
development using pandas and scikit-learn. Experienced in building RAG systems and exploring Agentic AI
workflows with LLMs. Proficient in data visualization and deploying solutions using FastAPI and Docker.

EDUCATION
Faculty of Computers and Artificial Intelligence, Cairo University

Sep 2023 - Jun 2027
BS in Information Systems
• GPA: 3.15 / 4.00

EXPERIENCE
Machine Learning Trainee


Nov 2025 – Present
Digital Egypt Pioneers Initiative


Cairo, Egypt

• Trained in data science, machine learning, and AI through hands-on projects
• Developed ML solutions using Python, including data preprocessing, feature engineering, and model
evaluation
• Explored LLM applications, including basic RAG pipelines and AI-driven workflows
Advanced Data Analytics Trainee


Jun 2025 – Jul 2025
NTI/ITIDA



Cairo, Egypt
• Contribute to AI workshops and technical initiatives.
• Collaborate on projects to enhance ML and problem-solving skills.


SKILLS
Technical Skills:
Programming Languages: Python, C++, C, Java, HTML, CSS, JavaScript
Data Science & Machine Learning: Machine learning, feature engineering, model evaluation, statistical
analysis, data wrangling, exploratory data analysis (EDA), data visualization, pandas, NumPy, scikit-learn,
matplotlib, seaborn
AI & LLM Technologies: LangChain, LangGraph, Retrieval-Augmented Generation (RAG) systems, LLM
applications, Agentic AI workflows
Databases & Backend Technologies: Microsoft SQL Server, FastAPI
Tools & Platforms: Git, GitHub, Docker, Microsoft SQL Server
Soft skills:
Professional Skills: Analytical and problem-solving mindset, team collaboration, time management, task
prioritization, technical communication, reporting, ability to work independently




PROJECTS
AI Support Ticket Assistant
• Built an AI-powered customer support system to assist agents in analyzing and resolving support
tickets, improving workflow efficiency by ~40% and reducing manual handling time.
• Developed a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue
categorization across multiple support categories.
• Designed an Agentic RAG pipeline using LangGraph and LLMs to generate contextaware solutions,
improving response relevance and quality by ~30–35%.
• Implemented a hybrid search retriever combining semantic (vector-based) and keyword search,
increasing retrieval precision and reducing irrelevant results by ~30%.  o Deployed the full application
using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support
with an interactive user interface.
Obesity Levels Analysis & Prediction
• Developed an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and
an optimized SVM model.
• Built and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker.

EXTRACURRICULAR ACTIVITIES
AI Committee Member | DSC, Cairo University
• Contribute to AI workshops and technical initiatives.
• Collaborate on projects to enhance ML and problem-solving skills.


COURSES
AI Data Science Diploma (160 Hours) Optical Soft Company

        Jul 2024 – Mar 2025
• Completed an intensive, industry-oriented diploma covering data analysis, machine learning, and
applied artificial intelligence
• Gained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and
model evaluation
• Applied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science
problems
• Achieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating

In [2]:
from langchain_core.documents import Document

In [13]:
def pdf_loader(folder_path):
    documnets = []
    for file in folder_path.glob("*.pdf"):
        doc = fitz.open(file)
        
        text = ""
        text += f"\n--- {file.name} ---"
        for page in doc:
            text += page.get_text()

        documnet = Document(page_content=text,metadata={'source':file})
        documnets.append(documnet)

    return documnets

In [2]:
from pathlib import Path
import fitz

In [15]:
docs = pdf_loader(Path("D:\Finance ChatBot\data_source\pdf_reports"))

In [16]:
len(docs)

2

In [9]:
print(docs)

[Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/pdf_reports/CV-MARWAN_TAMER_SAYED.pdf')}, page_content='\n--- CV-MARWAN_TAMER_SAYED.pdf ---MARWAN TAMER SAYED\nmarwantamer004@gmail.com\n01553278930\nLinkedIn | GitHub\nCairo, Egypt\nAspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python, machine learning, and\nstatistical analysis. Skilled in data preprocessing, feature engineering, and model development using pandas and scikit-learn. Experienced\nin building RAG systems and exploring Agentic AI workflows with LLMs. Proficient in data visualization and deploying solutions using\nFastAPI and Docker.\nExperience\nMachine Learning Trainee\nDigital Egypt Pioneers Initiative\nNov 2025 – present\nTrained in data science, machine learning, and AI through hands-on projects\nDeveloped ML solutions using Python, including data preprocessing, feature engineering, and model evaluation\nExplored LLM applications, including basic RAG pipelines and AI-driven workflows\nAdvanced Data Analytics Trainee\nNTI/ITIDA\nJun 2025 – Jul 2025\nCompleted 120-hour training in Python, ML, and data visualization\nApplied data-driven insights to solve practical problems\nAI Committee Member\nDSC, Cairo University\nNov 2025 – present\nContribute to AI workshops and technical initiatives\nCollaborate on projects to enhance ML and problem-solving skills\nEducation\nBachelor of Computer Science\nCairo University – Faculty of Computers and Artificial Intelligence\nGPA: 3.15 / 4.00\nProjects\nAI Support Ticket Assistant\nProject\nMay 2026\nBuilt an AI-powered customer support system to assist agents in analyzing and resolving support tickets, improving workflow\nefficiency by ~40% and reducing manual handling time\nDeveloped a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue categorization across multiple\nsupport categories\nDesigned an Agentic RAG pipeline using LangGraph and LLMs to generate context-aware solutions, improving response relevance and\nquality by ~30–35%\nImplemented a hybrid search retriever combining semantic (vector-based) and keyword search, increasing retrieval precision and\nreducing irrelevant results by ~30%\nDeployed the full application using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support\nwith an interactive user interface\nObesity Levels Analysis & Prediction\nProject\nAug 2025\nDeveloped an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and an optimized SVM model\nBuilt and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker\nCertifications\nAI Data Science Diploma\nJul 2024 – Mar 2025\nCompleted an intensive, industry-oriented diploma covering data analysis, machine learning, and applied artificial intelligence\nGained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and model evaluation\nApplied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science problems\nAchieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating\nSkills\nPython - Beginner\nC++ - Beginner\nC - Beginner\nJava - Beginner\nHTML - Beginner\nCSS - Beginner\nJavaScript -\nBeginner\nMachine learning - Beginner\nFeature engineering - Beginner\nModel evaluation - Beginner\nStatistical analysis -\nBeginner\nData wrangling - Beginner\nExploratory data analysis (EDA) - Beginner\nData visualization - Beginner\npandas -\nBeginner\nNumPy - Beginner\nscikit-learn - Beginner\nmatplotlib - Beginner\nseaborn - Beginner\nLangChain -\nBeginner\nLangGraph - Beginner\nRetrieval-Augmented Generation (RAG) systems - Beginner\nLLM applications -\nBeginner\nAgentic AI workflows - Beginner\nMicrosoft SQL Server - Beginner\nFastAPI - Beginner\nGit - Beginner\nGitHub -\nBeginner\nDocker - Beginner\nAnalytical and problem-solving mindset - Beginner\nTeam collaboration - Beginner\nTime\nmanagement - Beginner\nTask prioritization - Beginner\nTechnical communication - Beginner\nReporting - Beginner\nAbility to\nwork independently - Beginner\nLanguages\nEnglish\n'), Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/pdf_reports/Marwan Tamer Resume.pdf')}, page_content='\n--- Marwan Tamer Resume.pdf --- \n \nMARWAN TAMER SAYED  \nCairo, Egypt | marwantamer004@gmail.com | 01553278930 | LinkedIn |  GitHub  \nSummary \nAspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python, \nmachine learning, and statistical analysis. Skilled in data preprocessing, feature engineering, and model \ndevelopment using pandas and scikit-learn. Experienced in building RAG systems and exploring Agentic AI \nworkflows with LLMs. Proficient in data visualization and deploying solutions using FastAPI and Docker.  \n \nEDUCATION \nFaculty of Computers and Artificial Intelligence, Cairo University \n \nSep 2023 - Jun 2027 \nBS in Information Systems  \n• GPA: 3.15 / 4.00  \n \nEXPERIENCE \nMachine Learning Trainee \n \n \nNov 2025 – Present \nDigital Egypt Pioneers Initiative \n \n \nCairo, Egypt \n \n• Trained in data science, machine learning, and AI through hands-on projects \n• Developed ML solutions using Python, including data preprocessing, feature engineering, and model \nevaluation  \n• Explored LLM applications, including basic RAG pipelines and AI-driven workflows  \nAdvanced Data Analytics Trainee  \n \n \nJun 2025 – Jul 2025 \nNTI/ITIDA  \n \n \n \nCairo, Egypt \n• Contribute to AI workshops and technical initiatives.   \n• Collaborate on projects to enhance ML and problem-solving skills.     \n \n \nSKILLS \nTechnical Skills: \nProgramming Languages: Python, C++, C, Java, HTML, CSS, JavaScript \nData Science & Machine Learning: Machine learning, feature engineering, model evaluation, statistical \nanalysis, data wrangling, exploratory data analysis (EDA), data visualization, pandas, NumPy, scikit-learn, \nmatplotlib, seaborn  \nAI & LLM Technologies: LangChain, LangGraph, Retrieval-Augmented Generation (RAG) systems, LLM \napplications, Agentic AI workflows  \nDatabases & Backend Technologies: Microsoft SQL Server, FastAPI  \nTools & Platforms: Git, GitHub, Docker, Microsoft SQL Server  \nSoft skills:  \nProfessional Skills: Analytical and problem-solving mindset, team collaboration, time management, task \nprioritization, technical communication, reporting, ability to work independently  \n \n \n \n \nPROJECTS \nAI Support Ticket Assistant                              \n• Built an AI-powered customer support system to assist agents in analyzing and resolving support \ntickets, improving workflow efficiency by ~40% and reducing manual handling time.   \n• Developed a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue \ncategorization across multiple support categories.   \n• Designed an Agentic RAG pipeline using LangGraph and LLMs to generate contextaware solutions, \nimproving response relevance and quality by ~30–35%.   \n• Implemented a hybrid search retriever combining semantic (vector-based) and keyword search, \nincreasing retrieval precision and reducing irrelevant results by ~30%.  o Deployed the full application \nusing Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support \nwith an interactive user interface.  \nObesity Levels Analysis & Prediction \n• Developed an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and \nan optimized SVM model.   \n• Built and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker.  \n \nEXTRACURRICULAR ACTIVITIES \nAI Committee Member | DSC, Cairo University \n• Contribute to AI workshops and technical initiatives.   \n• Collaborate on projects to enhance ML and problem-solving skills.     \n  \n \nCOURSES \nAI Data Science Diploma (160 Hours) Optical Soft Company  \n \n        Jul 2024 – Mar 2025 \n• Completed an intensive, industry-oriented diploma covering data analysis, machine learning, and \napplied artificial intelligence   \n• Gained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and \nmodel evaluation   \n• Applied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science \nproblems   \n• Achieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating   \n \n')]

In [22]:
print(docs[0].page_content)

--- Marwan Tamer Resume.pdf ---

MARWAN TAMER SAYED
Cairo, Egypt | marwantamer004@gmail.com | 01553278930 | LinkedIn |  GitHub
Summary
Aspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python,
machine learning, and statistical analysis. Skilled in data preprocessing, feature engineering, and model
development using pandas and scikit-learn. Experienced in building RAG systems and exploring Agentic AI
workflows with LLMs. Proficient in data visualization and deploying solutions using FastAPI and Docker.

EDUCATION
Faculty of Computers and Artificial Intelligence, Cairo University

Sep 2023 - Jun 2027
BS in Information Systems
• GPA: 3.15 / 4.00

EXPERIENCE
Machine Learning Trainee


Nov 2025 – Present
Digital Egypt Pioneers Initiative


Cairo, Egypt

• Trained in data science, machine learning, and AI through hands-on projects
• Developed ML solutions using Python, including data preprocessing, feature engineering, and model
evaluation
• Explored LLM applications, including basic RAG pipelines and AI-driven workflows
Advanced Data Analytics Trainee


Jun 2025 – Jul 2025
NTI/ITIDA



Cairo, Egypt
• Contribute to AI workshops and technical initiatives.
• Collaborate on projects to enhance ML and problem-solving skills.


SKILLS
Technical Skills:
Programming Languages: Python, C++, C, Java, HTML, CSS, JavaScript
Data Science & Machine Learning: Machine learning, feature engineering, model evaluation, statistical
analysis, data wrangling, exploratory data analysis (EDA), data visualization, pandas, NumPy, scikit-learn,
matplotlib, seaborn
AI & LLM Technologies: LangChain, LangGraph, Retrieval-Augmented Generation (RAG) systems, LLM
applications, Agentic AI workflows
Databases & Backend Technologies: Microsoft SQL Server, FastAPI
Tools & Platforms: Git, GitHub, Docker, Microsoft SQL Server
Soft skills:
Professional Skills: Analytical and problem-solving mindset, team collaboration, time management, task
prioritization, technical communication, reporting, ability to work independently




PROJECTS
AI Support Ticket Assistant
• Built an AI-powered customer support system to assist agents in analyzing and resolving support
tickets, improving workflow efficiency by ~40% and reducing manual handling time.
• Developed a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue
categorization across multiple support categories.
• Designed an Agentic RAG pipeline using LangGraph and LLMs to generate contextaware solutions,
improving response relevance and quality by ~30–35%.
• Implemented a hybrid search retriever combining semantic (vector-based) and keyword search,
increasing retrieval precision and reducing irrelevant results by ~30%.  o Deployed the full application
using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support
with an interactive user interface.
Obesity Levels Analysis & Prediction
• Developed an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and
an optimized SVM model.
• Built and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker.

EXTRACURRICULAR ACTIVITIES
AI Committee Member | DSC, Cairo University
• Contribute to AI workshops and technical initiatives.
• Collaborate on projects to enhance ML and problem-solving skills.


COURSES
AI Data Science Diploma (160 Hours) Optical Soft Company

        Jul 2024 – Mar 2025
• Completed an intensive, industry-oriented diploma covering data analysis, machine learning, and
applied artificial intelligence
• Gained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and
model evaluation
• Applied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science
problems
• Achieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating

In [37]:
from PDF_Loader import pdf_loader

c:\Users\LOQ\anaconda3\envs\rag_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [38]:
chunks = pdf_loader("D:\Finance ChatBot\data_source\pdf_reports")

In [39]:
chunks

[Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\CV-MARWAN_TAMER_SAYED.pdf', 'page': 1, 'type': 'pdf'}, page_content='MARWAN TAMER SAYED\nmarwantamer004@gmail.com\n01553278930\nLinkedIn | GitHub\nCairo, Egypt\nAspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python, machine learning, and\nstatistical analysis. Skilled in data preprocessing, feature engineering, and model development using pandas and scikit-learn. Experienced\nin building RAG systems and exploring Agentic AI workflows with LLMs. Proficient in data visualization and deploying solutions using\nFastAPI and Docker.\nExperience\nMachine Learning Trainee\nDigital Egypt Pioneers Initiative\nNov 2025 – present\nTrained in data science, machine learning, and AI through hands-on projects\nDeveloped ML solutions using Python, including data preprocessing, feature engineering, and model evaluation\nExplored LLM applications, including basic RAG pipelines and AI-driven workflows\nAdvanced Data Analytics Trainee\nNTI/ITIDA\nJun 2025 – Jul 2025\nCompleted 120-hour training in Python, ML, and data visualization'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\CV-MARWAN_TAMER_SAYED.pdf', 'page': 1, 'type': 'pdf'}, page_content='Advanced Data Analytics Trainee\nNTI/ITIDA\nJun 2025 – Jul 2025\nCompleted 120-hour training in Python, ML, and data visualization\nApplied data-driven insights to solve practical problems\nAI Committee Member\nDSC, Cairo University\nNov 2025 – present\nContribute to AI workshops and technical initiatives\nCollaborate on projects to enhance ML and problem-solving skills\nEducation\nBachelor of Computer Science\nCairo University – Faculty of Computers and Artificial Intelligence\nGPA: 3.15 / 4.00\nProjects\nAI Support Ticket Assistant\nProject\nMay 2026\nBuilt an AI-powered customer support system to assist agents in analyzing and resolving support tickets, improving workflow\nefficiency by ~40% and reducing manual handling time\nDeveloped a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue categorization across multiple\nsupport categories\nDesigned an Agentic RAG pipeline using LangGraph and LLMs to generate context-aware solutions, improving response relevance and'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\CV-MARWAN_TAMER_SAYED.pdf', 'page': 1, 'type': 'pdf'}, page_content='support categories\nDesigned an Agentic RAG pipeline using LangGraph and LLMs to generate context-aware solutions, improving response relevance and\nquality by ~30–35%\nImplemented a hybrid search retriever combining semantic (vector-based) and keyword search, increasing retrieval precision and\nreducing irrelevant results by ~30%\nDeployed the full application using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support\nwith an interactive user interface\nObesity Levels Analysis & Prediction\nProject\nAug 2025\nDeveloped an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and an optimized SVM model\nBuilt and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker\nCertifications\nAI Data Science Diploma\nJul 2024 – Mar 2025\nCompleted an intensive, industry-oriented diploma covering data analysis, machine learning, and applied artificial intelligence'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\CV-MARWAN_TAMER_SAYED.pdf', 'page': 1, 'type': 'pdf'}, page_content='Certifications\nAI Data Science Diploma\nJul 2024 – Mar 2025\nCompleted an intensive, industry-oriented diploma covering data analysis, machine learning, and applied artificial intelligence\nGained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and model evaluation\nApplied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science problems\nAchieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating\nSkills\nPython - Beginner\nC++ - Beginner\nC - Beginner\nJava - Beginner\nHTML - Beginner\nCSS - Beginner\nJavaScript -\nBeginner\nMachine learning - Beginner\nFeature engineering - Beginner\nModel evaluation - Beginner\nStatistical analysis -\nBeginner\nData wrangling - Beginner\nExploratory data analysis (EDA) - Beginner\nData visualization - Beginner\npandas -\nBeginner\nNumPy - Beginner\nscikit-learn - Beginner\nmatplotlib - Beginner\nseaborn - Beginner\nLangChain -\nBeginner\nLangGraph - Beginner'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\CV-MARWAN_TAMER_SAYED.pdf', 'page': 1, 'type': 'pdf'}, page_content='Data visualization - Beginner\npandas -\nBeginner\nNumPy - Beginner\nscikit-learn - Beginner\nmatplotlib - Beginner\nseaborn - Beginner\nLangChain -\nBeginner\nLangGraph - Beginner\nRetrieval-Augmented Generation (RAG) systems - Beginner\nLLM applications -\nBeginner\nAgentic AI workflows - Beginner\nMicrosoft SQL Server - Beginner\nFastAPI - Beginner\nGit - Beginner\nGitHub -\nBeginner\nDocker - Beginner\nAnalytical and problem-solving mindset - Beginner\nTeam collaboration - Beginner\nTime\nmanagement - Beginner\nTask prioritization - Beginner\nTechnical communication - Beginner\nReporting - Beginner\nAbility to\nwork independently - Beginner\nLanguages\nEnglish'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 1, 'type': 'pdf'}, page_content='MARWAN TAMER SAYED  \nCairo, Egypt | marwantamer004@gmail.com | 01553278930 | LinkedIn |  GitHub  \nSummary \nAspiring Data Scientist and final-year Computer Science student at Cairo University with experience in Python, \nmachine learning, and statistical analysis. Skilled in data preprocessing, feature engineering, and model \ndevelopment using pandas and scikit-learn. Experienced in building RAG systems and exploring Agentic AI \nworkflows with LLMs. Proficient in data visualization and deploying solutions using FastAPI and Docker.  \n \nEDUCATION \nFaculty of Computers and Artificial Intelligence, Cairo University \n \nSep 2023 - Jun 2027 \nBS in Information Systems  \n• GPA: 3.15 / 4.00  \n \nEXPERIENCE \nMachine Learning Trainee \n \n \nNov 2025 – Present \nDigital Egypt Pioneers Initiative \n \n \nCairo, Egypt \n \n• Trained in data science, machine learning, and AI through hands-on projects \n• Developed ML solutions using Python, including data preprocessing, feature engineering, and model'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 1, 'type': 'pdf'}, page_content='Cairo, Egypt \n \n• Trained in data science, machine learning, and AI through hands-on projects \n• Developed ML solutions using Python, including data preprocessing, feature engineering, and model \nevaluation  \n• Explored LLM applications, including basic RAG pipelines and AI-driven workflows  \nAdvanced Data Analytics Trainee  \n \n \nJun 2025 – Jul 2025 \nNTI/ITIDA  \n \n \n \nCairo, Egypt \n• Contribute to AI workshops and technical initiatives.   \n• Collaborate on projects to enhance ML and problem-solving skills.     \n \n \nSKILLS \nTechnical Skills: \nProgramming Languages: Python, C++, C, Java, HTML, CSS, JavaScript \nData Science & Machine Learning: Machine learning, feature engineering, model evaluation, statistical \nanalysis, data wrangling, exploratory data analysis (EDA), data visualization, pandas, NumPy, scikit-learn, \nmatplotlib, seaborn  \nAI & LLM Technologies: LangChain, LangGraph, Retrieval-Augmented Generation (RAG) systems, LLM \napplications, Agentic AI workflows'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 1, 'type': 'pdf'}, page_content='matplotlib, seaborn  \nAI & LLM Technologies: LangChain, LangGraph, Retrieval-Augmented Generation (RAG) systems, LLM \napplications, Agentic AI workflows  \nDatabases & Backend Technologies: Microsoft SQL Server, FastAPI  \nTools & Platforms: Git, GitHub, Docker, Microsoft SQL Server  \nSoft skills:  \nProfessional Skills: Analytical and problem-solving mindset, team collaboration, time management, task \nprioritization, technical communication, reporting, ability to work independently'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 2, 'type': 'pdf'}, page_content='PROJECTS \nAI Support Ticket Assistant                              \n• Built an AI-powered customer support system to assist agents in analyzing and resolving support \ntickets, improving workflow efficiency by ~40% and reducing manual handling time.   \n• Developed a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue \ncategorization across multiple support categories.   \n• Designed an Agentic RAG pipeline using LangGraph and LLMs to generate contextaware solutions, \nimproving response relevance and quality by ~30–35%.   \n• Implemented a hybrid search retriever combining semantic (vector-based) and keyword search, \nincreasing retrieval precision and reducing irrelevant results by ~30%.  o Deployed the full application \nusing Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support \nwith an interactive user interface.  \nObesity Levels Analysis & Prediction'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 2, 'type': 'pdf'}, page_content='using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support \nwith an interactive user interface.  \nObesity Levels Analysis & Prediction \n• Developed an end-to-end ML system for predicting obesity categories using EDA, preprocessing, and \nan optimized SVM model.   \n• Built and deployed a FastAPI backend with a real-time prediction endpoint, containerized using Docker.  \n \nEXTRACURRICULAR ACTIVITIES \nAI Committee Member | DSC, Cairo University \n• Contribute to AI workshops and technical initiatives.   \n• Collaborate on projects to enhance ML and problem-solving skills.     \n  \n \nCOURSES \nAI Data Science Diploma (160 Hours) Optical Soft Company  \n \n        Jul 2024 – Mar 2025 \n• Completed an intensive, industry-oriented diploma covering data analysis, machine learning, and \napplied artificial intelligence   \n• Gained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and \nmodel evaluation'),
 Document(metadata={'source': 'D:\\Finance ChatBot\\data_source\\pdf_reports\\Marwan Tamer Resume.pdf', 'page': 2, 'type': 'pdf'}, page_content='applied artificial intelligence   \n• Gained hands-on experience in data preprocessing, EDA, feature engineering, supervised learning, and \nmodel evaluation   \n• Applied Python, NumPy, pandas, scikit-learn, and visualization tools to solve real-world data science \nproblems   \n• Achieved Excellent overall performance with a 92% final evaluation (Distinction) and 4.5/5 rating')]

## Shpread Sheets

In [1]:
import pandas as pd

In [33]:
from langchain_core.documents import Document

In [34]:
def csv_loader(folder_path):
    folder_path = Path(folder_path)
    documents = []
    for file in folder_path.glob('*.csv'):
        df = pd.read_csv(file)

        for _, row in df.iterrows():
            text = "\n".join(
                [f"{col}: {value}" for col, value in row.items()]
            )

            documents.append(
                Document(
                    page_content=text,
                    metadata={"source": file}
                )
            )

    return documents

In [35]:
data = csv_loader("D:\Finance ChatBot\data_source\erp_exports")

In [36]:
data

[Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 52\nParcel: 5\nTotal Customers: 57\nTotal Sales: 1140'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: samosa\nPrice: 12\nDine In: 10\nParcel: 12\nTotal Customers: 22\nTotal Sales: 264'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: samosa\nPrice: 12\nDine In: 23\nParcel: 0\nTotal Customers: 23\nTotal Sales: 276'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 29\nParcel: 24\nTotal Customers: 53\nTotal Sales: 1060'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 25\nParcel: 0\nTotal Customers: 25\nTotal Sales: 500'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 8\nParcel: 14\nTotal Customers: 22\nTotal Sales: 660'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 26\nParcel: 0\nTotal Customers: 26\nTotal Sales: 780'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: idli\nPrice: 20\nDine In: 11\nParcel: 10\nTotal Customers: 21\nTotal Sales: 420'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: idli\nPrice: 20\nDine In: 23\nParcel: 0\nTotal Customers: 23\nTotal Sales: 460'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 22\nParcel: 4\nTotal Customers: 26\nTotal Sales: 520'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/1/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 74\nParcel: 6\nTotal Customers: 80\nTotal Sales: 1600'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 47\nParcel: 6\nTotal Customers: 53\nTotal Sales: 1060'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: samosa\nPrice: 12\nDine In: 10\nParcel: 20\nTotal Customers: 30\nTotal Sales: 360'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: samosa\nPrice: 12\nDine In: 42\nParcel: 0\nTotal Customers: 42\nTotal Sales: 504'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 24\nParcel: 12\nTotal Customers: 36\nTotal Sales: 720'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 17\nParcel: 0\nTotal Customers: 17\nTotal Sales: 340'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 26\nParcel: 12\nTotal Customers: 38\nTotal Sales: 1140'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 29\nParcel: 0\nTotal Customers: 29\nTotal Sales: 870'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: idli\nPrice: 20\nDine In: 11\nParcel: 13\nTotal Customers: 24\nTotal Sales: 480'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: idli\nPrice: 20\nDine In: 42\nParcel: 0\nTotal Customers: 42\nTotal Sales: 840'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 30\nParcel: 23\nTotal Customers: 53\nTotal Sales: 1060'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/2/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 27\nParcel: 8\nTotal Customers: 35\nTotal Sales: 700'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 22\nParcel: 9\nTotal Customers: 31\nTotal Sales: 620'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: samosa\nPrice: 12\nDine In: 10\nParcel: 14\nTotal Customers: 24\nTotal Sales: 288'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: samosa\nPrice: 12\nDine In: 37\nParcel: 0\nTotal Customers: 37\nTotal Sales: 444'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 12\nParcel: 0\nTotal Customers: 12\nTotal Sales: 240'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 20\nParcel: 0\nTotal Customers: 20\nTotal Sales: 400'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 15\nParcel: 14\nTotal Customers: 29\nTotal Sales: 870'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 26\nParcel: 0\nTotal Customers: 26\nTotal Sales: 780'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: idli\nPrice: 20\nDine In: 10\nParcel: 23\nTotal Customers: 33\nTotal Sales: 660'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: idli\nPrice: 20\nDine In: 26\nParcel: 0\nTotal Customers: 26\nTotal Sales: 520'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 26\nParcel: 2\nTotal Customers: 28\nTotal Sales: 560'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/3/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 68\nParcel: 9\nTotal Customers: 77\nTotal Sales: 1540'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 41\nParcel: 7\nTotal Customers: 48\nTotal Sales: 960'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: samosa\nPrice: 12\nDine In: 11\nParcel: 11\nTotal Customers: 22\nTotal Sales: 264'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: samosa\nPrice: 12\nDine In: 35\nParcel: 0\nTotal Customers: 35\nTotal Sales: 420'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 25\nParcel: 27\nTotal Customers: 52\nTotal Sales: 1040'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 21\nParcel: 0\nTotal Customers: 21\nTotal Sales: 420'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 14\nParcel: 3\nTotal Customers: 17\nTotal Sales: 510'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 71\nParcel: 0\nTotal Customers: 71\nTotal Sales: 2130'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: idli\nPrice: 20\nDine In: 29\nParcel: 9\nTotal Customers: 38\nTotal Sales: 760'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: idli\nPrice: 20\nDine In: 14\nParcel: 0\nTotal Customers: 14\nTotal Sales: 280'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 23\nParcel: 21\nTotal Customers: 44\nTotal Sales: 880'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/4/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 54\nParcel: 6\nTotal Customers: 60\nTotal Sales: 1200'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 20\nParcel: 5\nTotal Customers: 25\nTotal Sales: 500'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: samosa\nPrice: 12\nDine In: 28\nParcel: 2\nTotal Customers: 30\nTotal Sales: 360'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: samosa\nPrice: 12\nDine In: 19\nParcel: 0\nTotal Customers: 19\nTotal Sales: 228'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 15\nParcel: 30\nTotal Customers: 45\nTotal Sales: 900'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 19\nParcel: 0\nTotal Customers: 19\nTotal Sales: 380'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 8\nParcel: 15\nTotal Customers: 23\nTotal Sales: 690'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 71\nParcel: 0\nTotal Customers: 71\nTotal Sales: 2130'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: idli\nPrice: 20\nDine In: 16\nParcel: 30\nTotal Customers: 46\nTotal Sales: 920'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: idli\nPrice: 20\nDine In: 13\nParcel: 0\nTotal Customers: 13\nTotal Sales: 260'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 10\nParcel: 6\nTotal Customers: 16\nTotal Sales: 320'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/5/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 27\nParcel: 8\nTotal Customers: 35\nTotal Sales: 700'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 44\nParcel: 9\nTotal Customers: 53\nTotal Sales: 1060'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: samosa\nPrice: 12\nDine In: 21\nParcel: 22\nTotal Customers: 43\nTotal Sales: 516'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: samosa\nPrice: 12\nDine In: 28\nParcel: 0\nTotal Customers: 28\nTotal Sales: 336'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 25\nParcel: 19\nTotal Customers: 44\nTotal Sales: 880'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 27\nParcel: 0\nTotal Customers: 27\nTotal Sales: 540'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 20\nParcel: 20\nTotal Customers: 40\nTotal Sales: 1200'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 42\nParcel: 0\nTotal Customers: 42\nTotal Sales: 1260'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: idli\nPrice: 20\nDine In: 21\nParcel: 6\nTotal Customers: 27\nTotal Sales: 540'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: idli\nPrice: 20\nDine In: 47\nParcel: 0\nTotal Customers: 47\nTotal Sales: 940'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 27\nParcel: 21\nTotal Customers: 48\nTotal Sales: 960'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/6/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 36\nParcel: 8\nTotal Customers: 44\nTotal Sales: 880'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 28\nParcel: 8\nTotal Customers: 36\nTotal Sales: 720'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: samosa\nPrice: 12\nDine In: 9\nParcel: 4\nTotal Customers: 13\nTotal Sales: 156'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: samosa\nPrice: 12\nDine In: 31\nParcel: 0\nTotal Customers: 31\nTotal Sales: 372'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 27\nParcel: 10\nTotal Customers: 37\nTotal Sales: 740'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 30\nParcel: 0\nTotal Customers: 30\nTotal Sales: 600'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 28\nParcel: 9\nTotal Customers: 37\nTotal Sales: 1110'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 32\nParcel: 0\nTotal Customers: 32\nTotal Sales: 960'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: idli\nPrice: 20\nDine In: 29\nParcel: 24\nTotal Customers: 53\nTotal Sales: 1060'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: idli\nPrice: 20\nDine In: 13\nParcel: 0\nTotal Customers: 13\nTotal Sales: 260'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 20\nParcel: 14\nTotal Customers: 34\nTotal Sales: 680'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/7/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 67\nParcel: 8\nTotal Customers: 75\nTotal Sales: 1500'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: tarri poha\nPrice: 20\nDine In: 27\nParcel: 7\nTotal Customers: 34\nTotal Sales: 680'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: samosa\nPrice: 12\nDine In: 12\nParcel: 29\nTotal Customers: 41\nTotal Sales: 492'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: samosa\nPrice: 12\nDine In: 32\nParcel: 0\nTotal Customers: 32\nTotal Sales: 384'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 17\nParcel: 16\nTotal Customers: 33\nTotal Sales: 660'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: bread pakoda\nPrice: 20\nDine In: 17\nParcel: 0\nTotal Customers: 17\nTotal Sales: 340'),
 Document(metadata={'source': WindowsPath('D:/Finance ChatBot/data_source/erp_exports/restaurant_data.csv')}, page_content='Date: 10/8/2023\nDish Name: aloo paratha\nPrice: 30\nDine In: 15\nParcel: 3\nTotal Customers: 18\nTotal Sales: 540'),

In [7]:
df= pd.read_csv(r"D:\Finance ChatBot\data_source\erp_exports\restaurant_data.csv")
df.head()

,Date,Dish Name,Price,Dine In,Parcel,Total Customers,Total Sales
0,10/1/2023,tarri poha,20,52,5,57,1140
1,10/1/2023,samosa,12,10,12,22,264
2,10/1/2023,samosa,12,23,0,23,276
3,10/1/2023,bread pakoda,20,29,24,53,1060
4,10/1/2023,bread pakoda,20,25,0,25,500

In [16]:
data = df.to_json()

In [23]:
df

,Date,Dish Name,Price,Dine In,Parcel,Total Customers,Total Sales
0,10/1/2023,tarri poha,20,52,5,57,1140
1,10/1/2023,samosa,12,10,12,22,264
2,10/1/2023,samosa,12,23,0,23,276
3,10/1/2023,bread pakoda,20,29,24,53,1060
4,10/1/2023,bread pakoda,20,25,0,25,500
...,...,...,...,...,...,...,...
644,11/28/2023,aloo paratha,30,48,0,48,1440
645,11/28/2023,idli,20,27,10,37,740
646,11/28/2023,idli,20,51,0,51,1020
647,11/28/2023,boiled eggs,20,24,29,53,1060
648,11/28/2023,boiled eggs,20,26,10,36,720

In [29]:
text = ""
for _, row in df.iterrows():
    text = "\n".join(
                [f"{col}: {value}" for col, value in row.items()]
            )

In [30]:
text

'Date: 11/28/2023\nDish Name: boiled eggs\nPrice: 20\nDine In: 26\nParcel: 10\nTotal Customers: 36\nTotal Sales: 720'

## embeding ##

In [3]:
from langchain_ollama import OllamaEmbeddings

embeddings = OllamaEmbeddings(
    model="nomic-embed-text"
)

In [5]:
len(embeddings.embed_query("how are u today ?"))

768

In [8]:
import os
from langchain_community.vectorstores import Chroma

BASE_DB_DIR = os.path.abspath("../chroma_dbs")

def create_vector_store(chunks, db_name="default_db"):
    db_path = os.path.join(BASE_DB_DIR, db_name)

    # Create folder if it doesn't exist
    os.makedirs(db_path, exist_ok=True)

    # Check if Chroma DB already exists
    if os.listdir(db_path):
        print(f"Loading existing DB: {db_name}")

        vector_store = Chroma(
            persist_directory=db_path,
            embedding_function=embeddings
        )

        # Add new documents
        vector_store.add_documents(chunks)

    else:
        print(f"Creating new DB: {db_name}")

        vector_store = Chroma.from_documents(
            documents=chunks,
            embedding=embeddings,
            persist_directory=db_path
        )

    vector_store.persist()

    return vector_store

In [9]:
from PDF_Loader import pdf_loader
chunks = pdf_loader("D:\\final project\\Finance-Agent\\data_source\\pdf_reports")

In [13]:
db=create_vector_store(chunks, db_name="pdf_reports_db")

Creating new DB: pdf_reports_db

C:\Users\pc\AppData\Local\Temp\ipykernel_2292\3651463585.py:33: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  vector_store.persist()

In [25]:
test1=db.similarity_search("depi")

In [29]:
print(test1[2].page_content)

Data visualization - Beginner
pandas -
Beginner
NumPy - Beginner
scikit-learn - Beginner
matplotlib - Beginner
seaborn - Beginner
LangChain -
Beginner
LangGraph - Beginner
Retrieval-Augmented Generation (RAG) systems - Beginner
LLM applications -
Beginner
Agentic AI workflows - Beginner
Microsoft SQL Server - Beginner
FastAPI - Beginner
Git - Beginner
GitHub -
Beginner
Docker - Beginner
Analytical and problem-solving mindset - Beginner
Team collaboration - Beginner
Time
management - Beginner
Task prioritization - Beginner
Technical communication - Beginner
Reporting - Beginner
Ability to
work independently - Beginner
Languages
English

In [34]:
retriever = db.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 3,
        "fetch_k": 10,
        "lambda_mult": 0.5
    }
)

In [40]:
test2=retriever.invoke("AI Support Ticket Assistant  ")

In [42]:
print(test2[1].page_content)

PROJECTS
AI Support Ticket Assistant
• Built an AI-powered customer support system to assist agents in analyzing and resolving support
tickets, improving workflow efficiency by ~40% and reducing manual handling time.
• Developed a DistilBERT-based text classification model achieving ~90%+ accuracy for automatic issue
categorization across multiple support categories.
• Designed an Agentic RAG pipeline using LangGraph and LLMs to generate contextaware solutions,
improving response relevance and quality by ~30–35%.
• Implemented a hybrid search retriever combining semantic (vector-based) and keyword search,
increasing retrieval precision and reducing irrelevant results by ~30%.  o Deployed the full application
using Streamlit, enabling real-time predictions, confidence scores, and AI-assisted resolution support
with an interactive user interface.
Obesity Levels Analysis & Prediction